const DEFAULT_LATITUDE = 37.497256272176;
const DEFAULT_LONGITUDE = 127.03205058551;
const DEFAULT_ZOOM_SCALE = 15;
const DEFAULT_MAX_ZOOM = 15;
const DEFAULT_MIN_ZOOM = 11;
const KM_TO_M_CONVERSION_FACTOR = 1000;
const MIN_RADIUS = 0;
const MAX_RADIUS = 10;
const DROP = 2;

export {
  DEFAULT_LATITUDE,
  DEFAULT_LONGITUDE,
  DEFAULT_MAX_ZOOM,
  DEFAULT_MIN_ZOOM,
  DEFAULT_ZOOM_SCALE,
  KM_TO_M_CONVERSION_FACTOR,
  MIN_RADIUS,
  MAX_RADIUS,
  DROP,
};
